OP_LABEL(op_pop);
OP_LABEL(op_dup);
OP_LABEL(op_constant);
OP_LABEL(op_constant_long);

OP_LABEL(op_value);
OP_LABEL(op_none);
OP_LABEL(op_true);
OP_LABEL(op_false);

OP_LABEL(op_not);
OP_LABEL(op_negate);
OP_LABEL(op_equal);
OP_LABEL(op_not_equal);
OP_LABEL(op_less);
OP_LABEL(op_less_equal);
OP_LABEL(op_greater);
OP_LABEL(op_greater_equal);
OP_LABEL(op_add);
OP_LABEL(op_subtract);
OP_LABEL(op_multiply);
OP_LABEL(op_divide);

OP_LABEL(op_bw_and);
OP_LABEL(op_bw_or);
OP_LABEL(op_bw_xor);
OP_LABEL(op_bw_sl);
OP_LABEL(op_bw_sr);
OP_LABEL(op_bw_not);

OP_LABEL(op_define_global);
OP_LABEL(op_get_global);
OP_LABEL(op_set_global);
OP_LABEL(op_get_local);
OP_LABEL(op_set_local);
OP_LABEL(op_get_upvalue);
OP_LABEL(op_set_upvalue);

OP_LABEL(op_get_property);
OP_LABEL(op_set_property);
OP_LABEL(op_get_super);
OP_LABEL(op_get_layer_property);
OP_LABEL(op_get_type);

OP_LABEL(op_jump_if_false);
OP_LABEL(op_jump_if_neq);
OP_LABEL(op_jump);
OP_LABEL(op_loop);
OP_LABEL(op_call);

OP_LABEL(op_closure);
OP_LABEL(op_close_upvalue);

OP_LABEL(op_print);
OP_LABEL(op_return);
OP_LABEL(op_break);
OP_LABEL(op_continue);
OP_LABEL(op_match);

OP_LABEL(op_class);
OP_LABEL(op_method);
OP_LABEL(op_inherit);
OP_LABEL(op_invoke);
OP_LABEL(op_super_invoke);
OP_LABEL(op_struct);
OP_LABEL(op_member);
OP_LABEL(op_struct_inherit);

OP_LABEL(op_enum);
OP_LABEL(op_enum_define_member);
OP_LABEL(op_enum_get_member);
OP_LABEL(op_enum_member_bind);
OP_LABEL(op_enum_member_match);

OP_LABEL(op_layer_property_call);
OP_LABEL(op_vector_new);
OP_LABEL(op_vector_set);
OP_LABEL(op_vector_get);
